matriz/core/urls.py
from django.urls import path
from . import views
from .views import HomePageView,CategoriaListView,CategoriaDetail, TablaDetail, GuardiasEspecialistasListView,GuardiasEspecialistasUpdateView, GuardiasEspecialistasDeleteView,GuardiaSemanalCreate, GuardiaListView, GuardiaDetail



app_name= 'core'
urlpatterns = [
	path('', HomePageView.as_view(), name="home"),
	path('categorias/', CategoriaListView.as_view(), name="categoria_list"),
	path('<int:pk>/', CategoriaDetail.as_view(), name="categoria_detail"),
	path('tabla/<int:pk>/', TablaDetail.as_view(), name="tabla_detail"),

	path('create_guardia_semanal/', GuardiaSemanalCreate.as_view(), name='guardiaSemanal_create'),

	path('guardias/especialistas/', GuardiasEspecialistasListView.as_view(), name="guardias_especialistas_list"),
	path('guardias/especialistas/update/<int:pk>/', GuardiasEspecialistasUpdateView.as_view(), name="guardias_especialistas_update"),
	path('guardias/especialistas/delete/<int:pk>/', GuardiasEspecialistasDeleteView.as_view(), name="guardias_especialistas_delete"),

	path('guardias/soportes/', GuardiaListView.as_view(), name="guardias_soportes_list"),

	path('guardia/<int:pk>/', GuardiaDetail.as_view(), name="guardia_detail"),



]

matriz/matriz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from registration import views

urlpatterns = [
    path('', include('core.urls')),

    path("logout", views.logout_request, name= "logout"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

#Nos permite servir ficheros estaticos
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

matriz/core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
# Create your models here.

NIVEL = (
    (1, 'Especialista'),
    (2, 'Supervisor'),
    (3, 'Jefe de área'),
    (4, 'Gerente de área'),
    (5, 'Gerente'),
)

def extensiones_validas(value):
    value = str(value)
    extensiones_validas = ['jpg', 'jpeg', 'png']
    extension = value.split('.')[1].lower()

    if extension not in extensiones_validas:
        raise ValidationError("Archivos permitidos: .jpg, .jpeg, .png")


def extensiones_validas_adjunto(value):
    value = str(value)
    extensiones_validas = ['pdf']
    extension = value.split('.')[1].lower()

    if extension not in extensiones_validas:
        raise ValidationError("Solo permitimos archivos: .pdf")


class Categoria(models.Model):
    name  = models.CharField(max_length=200, verbose_name="Nombre de la Categoria", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["-created"]

    def __str__(self):
        return self.name



class Empresa(models.Model):
    name  = models.CharField(max_length=200, verbose_name="Nombre", blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="get_categoria",
                                verbose_name="Categoria")

    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Empresa"
        verbose_name_plural = "Empresas"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["-created"]

    def __str__(self):
        return self.name


class TablaEscalacion(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="get_empresa",
                                verbose_name="Empresa")
    excel = models.FileField(max_length=200, verbose_name="Adjunta El documento", upload_to= 'documents', blank=True, null=True, validators=[extensiones_validas_adjunto])

    imagen = models.ImageField(verbose_name='Adjunta una imagen', upload_to='empresa', blank=True, null=True, validators=[extensiones_validas])

    comentario = models.TextField( verbose_name="Comentarios", blank=True, null=True)



    class Meta:
        verbose_name = "Tabla de Escalación"
        verbose_name_plural = "Tablas de Escalaciones"

    def __str__(self):
        return self.empresa.name




class Guardia(models.Model):
    name  = models.CharField(max_length=200, verbose_name="Nombre", blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="get_user", verbose_name="Usuario Asociado",
                             blank=True, null=True)

    escalacion = models.ForeignKey(TablaEscalacion, on_delete=models.CASCADE, related_name="get_escalacion",
                                verbose_name="Escalación", blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Guardia"
        verbose_name_plural = "Guardias"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["name"]

    def __str__(self):
        return self.name

# Create your models here.







class GuardiaEspecialista(models.Model):
    guardia = models.ForeignKey(Guardia, on_delete=models.CASCADE, related_name="get_especialistas",
                              verbose_name="Seleccione el especialista", blank=True, null=True)

    imagen = models.ImageField(verbose_name='Adjunta una imagen', upload_to='empresa', blank=True, null=True,
                               validators=[extensiones_validas])

    fecha_inicio = models.DateField(verbose_name="Fecha Inicio", blank=True, null=True)
    fecha_fin = models.DateField(verbose_name="Fecha Fin", blank=True, null=True)

    comentario = models.TextField(verbose_name="Comentarios", blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")


    class Meta:
        verbose_name = "Guardia por Especialista"
        verbose_name_plural = "Guardias por Especialistas"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["-fecha_inicio",]

    def __str__(self):
        return str(self.guardia.name)

matriz/core/forms.py
from django import forms
from .models import GuardiaEspecialista



class GuardiaEspecialistaForm(forms.ModelForm):
    class Meta:
        model = GuardiaEspecialista
        fields = ['guardia', 'imagen','comentario','fecha_inicio','fecha_fin']
        widgets = {

            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control-file mt-3'}),
            'comentario': forms.Textarea(attrs={'class': 'form-control mt-3', 'rows': 3, 'placeholder': 'Escriba algún comentario'}),
            'fecha_inicio': forms.TextInput(attrs={'class': 'form-control mt-3', 'placeholder':'aaaa-mm-dd 00:00:00', 'required': 'True','type':'date'}),
            'fecha_fin': forms.TextInput(attrs={'class': 'form-control mt-3', 'placeholder':'aaaa-mm-dd 00:00:00','required': 'True', 'type':'date'}),

        }

        labels = {
            'fecha_inicio': 'Fecha de Inicio',
        }

matriz/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import *
from django.views.generic.list import ListView, MultipleObjectMixin
from django.views.generic.detail import DetailView
from .forms import  GuardiaEspecialistaForm
from django.views.generic.edit import  CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse



now = timezone.now()
# Create your views here.


# Vista para la pagina Home y ordenar productos en la portada

class HomePageView(TemplateView):
    template_name = "core/base.html"


class CategoriaListView(ListView):
    template_name = "core/index.html"
    model = Categoria

    def get_queryset(self):
        object_list = Categoria.objects.all()
        queryset = self.request.GET.get('search')
        if queryset:
            object_list = Categoria.objects.filter(
                Q(name__icontains=queryset)
            ).distinct()
        return object_list


class CategoriaDetail(DetailView, MultipleObjectMixin):
    template_name = "core/empresa.html"
    model = Categoria

    def get_context_data(self, **kwargs):
        object_list = Empresa.objects.filter(categoria_id=self.object.id)
        context = super(CategoriaDetail, self).get_context_data(object_list=object_list, **kwargs)
        queryset = self.request.GET.get('search')
        if queryset:
            object_list = Empresa.objects.filter(categoria_id=self.object.id).filter(
                Q(name__icontains=queryset)
            ).distinct()
            context = super(CategoriaDetail, self).get_context_data(object_list=object_list, **kwargs)

        return context




class TablaDetail(DetailView):
    template_name = "core/tabla.html"
    model = Empresa


    def get_context_data(self, **kwargs):
        object_list = TablaEscalacion.objects.filter(empresa_id=self.object.id)
        context = super(TablaDetail, self).get_context_data(object_list=object_list, **kwargs)
        return context



class GuardiaListView(ListView):
    template_name = "core/guardia_list.html"
    model = Guardia

    def get_queryset(self):
        object_list = Guardia.objects.all()
        queryset = self.request.GET.get('search')
        if queryset:
            object_list = Guardia.objects.filter(
                Q(name__icontains=queryset)
            ).distinct()
        return object_list


class GuardiaDetail(DetailView):
    template_name = "core/guardia_detail.html"
    model = Guardia

    def get_context_data(self, **kwargs):
        object_list = GuardiaEspecialista.objects.filter(guardia_id=self.object.id).filter(fecha_inicio__lte=now).filter(fecha_fin__gte=now)
        context = super(GuardiaDetail, self).get_context_data(object_list=object_list, **kwargs)

        queryset = self.request.GET.get('search')
        if queryset:
            object_list =GuardiaEspecialista.objects.filter(guardia__id=self.object.id).filter(fecha_inicio__lte=now).filter(fecha_fin__gte=now).filter(
                Q(name__name__icontains=queryset)
            ).distinct()
            context = super(GuardiaDetail, self).get_context_data(object_list=object_list, **kwargs)

        return context


class GuardiaSemanalCreate(CreateView):
    model = GuardiaEspecialista
    form_class = GuardiaEspecialistaForm
    template_name = "core/guardia_Semanal.html"

    def get_success_url(self):
        return reverse_lazy('core:guardiaSemanal_create') + "?ok"



class GuardiasEspecialistasListView(ListView):
    template_name = "core/guardias_especialidades_list.html"
    model = GuardiaEspecialista
    paginate_by = 4

    def get_context_data(self, **kwargs):
        object_list = GuardiaEspecialista.objects.filter(id=self.request.user.get_user.id)
        context = super(GuardiasEspecialistasListView, self).get_context_data(object_list=object_list, **kwargs)
        return context



class GuardiasEspecialistasUpdateView(UpdateView):
    template_name = "core/guardias_especialidades_update.html"
    model = GuardiaEspecialista
    #fields = ['imagen','fecha_inicio','fecha_fin','guardia']
    form_class = GuardiaEspecialistaForm


    def get_success_url(self):
        return reverse_lazy('core:guardias_especialistas_update', args=[self.object.id]) + "?ok"






class GuardiasEspecialistasDeleteView(DeleteView):
    template_name = "core/guardias_especialidades_delete.html"
    model = GuardiaEspecialista
    success_url = reverse_lazy('core:guardias_especialistas_list')

matriz/core/templates/core/base.html
<!doctype html>
<html lang="es">
<head>  
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" type="#" href="#">
  {% load static %}
  <!-- ARCHIVOS CSS BOOTSTRAP 4 -->
  <link type="text/css" rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
  <!-- ARCHIVOS CSS PERSONALIZADOS -->
  <link type="text/css" rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
    <!-- ICONOS BOOSTRAP -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">


    {% block css_extra %}{% endblock %}

    <title>{% block title %}{% endblock %}  | Inetum</title>
</head>
<body>



   
    <!-- INICIO DE LA BARRA DE NAVEGACION -->
    <nav class="navbar navbar-dark  navbar-expand-md bg-secondary" >
      <div class="container">
        <a href="" class="navbar-brand">
          <img src="{% static 'core/images/inetum.png' %}" alt="Logo del sitio" width="150">
        </a>
          {% if not  request.path == '/create_guardia_semanal/' or not '/guardias/especialistas/'  %}
      <form class="d-flex ml-5 pl-5" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-primary ml-2" type="submit">Search</button>
      </form>


         {% endif %}



        {% if not request.user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link btn btn-outline-primary me-2">Login</a></li>
      </ul>
         {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item text-white mr-3 my-auto">Bienvenido {{user}}</li>
        <li class="nav-item"><a href="/logout" class="nav-link btn btn-outline-primary me-2">Logout</a></li>
             {% if request.user.is_staff %}
         <li class="nav-item ml-2"><a href="{% url 'core:guardiaSemanal_create'  %}" class="nav-link btn btn-outline-primary me-2" style="color:white;">Carga</a></li>
         {% endif %}
      </ul>
         {% endif  %}
      </div>
    </nav>
    <!-- /FIN DE LA BARRA DE NAVEGACION -->

    {% include 'registration/includes/messages.html' %}

        {% if  request.user.is_authenticated %}

         {% block content %}{% endblock %}
          {% endif  %}


         {% block login %}{% endblock %}


 
<!-- ARCHIVOS BOOTSTRAP JAVASCRIPT -->
<script src="{% static 'core/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'core/js/popper.min.js' %}"></script>
<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
 {% block calendario %}{% endblock %}
</body>
</html>

matriz/core/templates/core/empresa.html
{% extends 'core/base.html' %}
{% block title %}Empresas{% endblock %}
{% load static %}
{% load thumbnail %}
{% block content %}

       <!-- INICIO SECTION EMPRESAS -->
            <section class="proyectos py-4">
              <div class="container">
                <h6>
                    <a href="javascript:history.back()" class="text-muted">
                       <i class="bi bi-backspace-fill"></i> Regresar</a>
                </h6>
                <h4 class="font-weight-bold text-center pb-4">{{object}}</h4>
                <div class="row text-md-center">
                  {% for empresa in object_list %}
                  <article class="col-12 col-md-6 col-lg-3 mb-3 mb-lg-0">
                    <div class="card mt-2">
                      <div class="card-body">
                        <h5 class="card-title">{{empresa.name}}</h5>
                        <a href="{% url 'core:tabla_detail' empresa.id %}" class="btn btn-secondary">Ver Matriz</a>
                      </div>
                    </div>
                  </article>
                  {% endfor %}
                </div>
              </div>
            </section>
       <!-- /FIN DE LA SECTION -->
{% endblock %}

matriz/core/templates/core/guardia_Semanal.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Cargar Guardia{% endblock %}

{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form id = "formulario" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="row">

            <!-- Formulario -->
            <div class="col-md-10">
              <h3 class="text-center">Carga guardia {{request.user}}</h3>
              {% if 'ok' in request.GET %}
                <p style="color:green;">
                  Guardia cargada correctamente...
                </p>
              {% endif %}

              <input type="text" value="{{request.user.get_user.id}}" name="guardia" id="id_guardia" class="form-control mt-3" hidden>
              <input type="file" name="imagen" class="form-control-file mt-3" id="id_imagen">



              {{form.fecha_inicio}}
              {{form.fecha_fin}}
                {{ form.comentario }}




              <p class="mt-3">
                Quieres ver las guadias Cargadas <a  class="link-primary" href="{% url 'core:guardias_especialistas_list' %}">aquí</a>.<br>
                Home  <a  class="link-primary" href="{% url 'core:categoria_list'  %}">aquí</a>.
              </p>
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Cargar">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock %}

matriz/core/templates/core/guardia_detail.html
{% extends 'core/base.html' %}
{% block title %}Guardia detallada{% endblock %}
{% load static %}
{% load thumbnail %}
{% block content %}

 <div class="container mt-3">
    <div class="row">
        <div class="col-12 ">
            <h6 ><a href="javascript:history.back()" class="text-muted">
                       <i class="bi bi-backspace-fill"></i> Regresar
               </a>
                </h6>
             <h4 class="font-weight-bold text-center pb-4">{{object}} </h4>
            {% for guardia in object_list %}
            <div class="text-center">
                <img src="{% thumbnail guardia.imagen 800x0  quality=100 %}" class="img-fluid my-1" alt="...">
                </div>
            <p class="font-weight-bold mt-3">
                {{guardia.comentario}}
            </p>

             <p class="mt-3">
                Quieres ver la matriz de Escalación <a  class="link-primary" href="{% url 'core:tabla_detail' guardia.guardia.escalacion.empresa.id  %}">aquí</a>.<br>

              </p>
            {% endfor %}
        </div>
    </div>
 </div>
{% endblock %}

matriz/core/templates/core/guardia_list.html
{% extends 'core/base.html' %}
{% block title %}Guardias {% endblock %}
{% load static %}
{% load thumbnail %}
{% block content %}

       <!-- INICIO SECTION EMPRESAS -->
            <section class="proyectos py-4">
              <div class="container">
                <h6>
                    <a href="javascript:history.back()" class="text-muted">
                       <i class="bi bi-backspace-fill"></i> Regresar</a>
                </h6>
                <h4 class="font-weight-bold text-center pb-4">Guardias</h4>
                <div class="row text-md-center">
                  {% for empresa in object_list %}
                  <article class="col-12 col-md-6 col-lg-3 mb-3 mb-lg-0 mt-3">
                    <div class="card">
                        {% if empresa.imagen %}
                      <img class="card-img-top" src="{% thumbnail empresa.imagen 300x0 quality=100 %}" alt="{{empresa.name}}">
                        {% endif %}
                      <div class="card-body">
                        <h5 class="card-title">{{empresa.name}}</h5>
                        <a href="{% url 'core:guardia_detail' empresa.id %}" class="btn btn-secondary">Ver Guardia</a>
                      </div>
                    </div>
                  </article>
                  {% endfor %}
                </div>
              </div>
            </section>
       <!-- /FIN DE LA SECTION -->
{% endblock %}

matriz/core/templates/core/guardias_especialidades_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar Guardia{% endblock %}
{% block content %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          <form action="" method="post">{% csrf_token %}
            <p>¿Estás seguro de que quieres borrar la Guardia de <b>"{{ object.name }}"</b> con fecha de inicio <b>"{{ object.fecha_inicio }}"</b> y fin <b>"{{ object.fecha_fin }}"</b> ?</p>
            <input type="submit" class="btn btn-primary btn-block" value="Sí, borrar la guardia" />
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

matriz/core/templates/core/guardias_especialidades_list.html
{% extends 'core/base.html' %}
{% block title %}Guardias Especialistas{% endblock %}
{% load static %}
 {% block css_extra %}
    <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'core/plugins/fontawesome-free/css/all.min.css' %}">
{% endblock %}

{% block content %}
 <div class="container mt-3">
    <div class="row">
        <div class="col-12 ">
          <a href="javascript:history.back()" class="text-muted">
                       <i class="bi bi-backspace-fill"></i> Regresar
               </a>
           <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col" colspan="5" class="text-center">Guardias Cargadas </th>
              </tr>
                 <tr>

                     <td class="text-center">Fecha Inicio</td>
                     <td class="text-center">Fecha Fin</td>

                     <td></td>
              </tr>
            </thead>
            <tbody>
             {% for item in object_list  %}
              <tr>

                   <td class="text-center"> {{item.fecha_inicio}}</td>
                   <td class="text-center"> {{item.fecha_fin}}</td>


                  <td class="border px-2 py-2 text-center" >

                          <a class="btn btn-info btn-sm my-1" style="width:auto; " href="{% url 'core:guardias_especialistas_update' item.id  %}">
                              <i class="fas fa-pencil-alt">
                              </i><font _mstmutation="1" _msthash="3299387" _msttexthash="75699"> Editar </font></a>

                       <a class="btn btn-primary btn-sm my-1" style="width:auto;" href="{% url 'core:guardias_especialistas_delete' item.id %}">
                              <i class="fas fa-trash-alt"></i>
                                <font _mstmutation="1" _msthash="3299270" _msttexthash="61152"> Borrar  </font></a>
                       </td>

              </tr>
             {% endfor %}
            </tbody>
          </table>
        </div>
    </div>
 </div>


<!-- Menú de paginación -->
{% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item " >
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&laquo;</a>
        </li>
      {% endif %}
      {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %}" >
          <a class="page-link" href="?page={{ i }}" >{{ i }}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled" >
          <a class="page-link" href="#" tabindex="-1">&raquo;</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

{% endblock %}

matriz/core/templates/core/guardias_especialidades_update.html
{% extends 'core/base.html' %}
{% block title %}Editar Guardia{% endblock %}
{% load static %}


{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form id = "formulario" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="row">

            <!-- Formulario -->
            <div class="col-md-10">
              <h3 class="text-center">Editar guardia {{request.user}}</h3>
              {% if 'ok' in request.GET %}
                <p style="color:green;">
                  Guardia editada correctamente correctamente...
                  <a style="color:black;" href="{% url 'core:guardias_especialistas_list' %}">Haz clic aquí para ver el resultado</a>.
                </p>
              {% endif %}

              <input type="text" value="{{request.user.get_user.id}}" name="guardia" id="id_guardia" class="form-control mt-3" hidden>


               {{form.imagen}}

              {{form.fecha_inicio}}
              {{form.fecha_fin}}
                {{ form.comentario }}


              <input type="submit" class="btn btn-primary btn-block mt-3" value="Actualizar">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock %}

matriz/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Principal{% endblock %}
{% load static %}
{% block content %}


    <!-- INICIO DE LA TARJETA -->
        <div class="container"> 
          <div class="card text-center my-3">
            <div class="card-header">
              <ul class="nav nav-tabs card-header-tabs">
                {%  for object in object_list  %}
                <li class="nav-item">
                  <a class="nav-link categories" href="{% url 'core:categoria_detail' object.id %}">{{object}}</a>
                </li>
                {% endfor %}

                 <li class="nav-item">
                  <a class="nav-link categories" href="{% url 'core:guardias_soportes_list' %}">GUARDIAS</a>
                </li>
              </ul>
            </div>
            <div class="card-body">
              <h5 class="card-title">Matrices de Escalación</h5>
              <p class="card-text">El siguiente contenido es confidencial.</p>
            </div>
          </div>
        </div>
    <!-- /FIN DE LA TARJETA -->
{% endblock %}

matriz/core/templates/core/tabla.html
{% extends 'core/base.html' %}
{% block title %}Tablas{% endblock %}
{% load static %}
{% load thumbnail %}
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h6 class="mt-4"><a href="javascript:history.back()" class="text-muted">
                       <i class="bi bi-backspace-fill"></i> Regresar
               </a>
                </h6>

                {% for guardia in object_list %}


                 <h5 class=" font-weight-bold text-center">{{guardia.empresa.name}}</h5>


                <div class="text-center">
                 <img src="{% thumbnail guardia.imagen 800x0  quality=100 %}" class="img-fluid" alt="...">
                     </div>
                 {% if guardia.excel %}
                    <a href="{{ guardia.excel.url }}" download  class="btn btn-outline-secondary btn-lg btn-block mt-2" >Download</a>
                 {% endif %}

                {% if guardia.comentario %}


                   <p class="font-weight-bold mt-3">{{guardia.comentario}}</p>
                 {% endif %}

                {% endfor  %}

            </div>
        </div>
    </div>
</section>
{% endblock %}